### ISSUE TITLE
aim zoom

### ISSUE THREAD

**Issue by Levi-Diniz** [pepe033/pepe_celowniki#1]
Hello, how did you do to open the crosshairs like this, mine has the crosshairs on the right side and not with the crosshairs in the middle of the screen with the weapon next to it

This is a screenshot of your video
![image](https://github.com/user-attachments/assets/356a4b03-9746-4e13-a23f-32b1964cf3dd)

this is a screenshot in my game
![image](https://github.com/user-attachments/assets/e8b284e6-1038-44f5-9f5e-955515119bf4)

**Comment by pepe033** [comment]
isn't that the standard gta crosshair just showing up on the screen? the crosshair in the weapon is a built-in feature of gta and the only thing that has been added are the items to allow people to mount a scope onto a weapon, try to use a script that either disables the dot or just use profile_reticulesize -10 under f8
